### ISSUE TITLE
Error running node app.js

### ISSUE THREAD

**Issue by patan32** [smartcuc/COVID-19#11]
I am getting this error. 
node app.js
1(node:11965) UnhandledPromiseRejectionWarning: Error: getaddrinfo EAI_AGAIN xxxx:80
    at Object._errnoException (util.js:1022:11)
    at errnoException (dns.js:55:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
(node:11965) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:11965) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by ouinouin** [comment]
Same here : UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND xxxx xxxx:80
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
(node:91235) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:91235) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
since yesterday 1 april 2020

**Comment by smartcuc** [comment]
Have you made any changes to app.js? If not, please double check line 7 and 11.

**Comment by ouinouin** [comment]
hi , 
the hiccup is line 7 i had to comment it to make it run :
what is the purpose of the proxyagent ? do we need it if we re not behind a proxy ? 
regards .
line 7 :  
//         httpsAgent: new HttpsProxyAgent('http://XXXX:XXXX@XXXX:XXXX')

**Comment by smartcuc** [comment]
Yeah, you did it right.... No proxy => // that line...
